### PR TITLE
First draft of astroquery component

### PR DESCRIPTION
**Pull request by keflavich**
cc @bsipocz, @ceb8

I've just put in some text off the top of my head; I'm worried that I left out - or even incorrectly added - some institutes here.

@adrn I added the \paperii command, but probably that suggestion deserves to be centralized somewhere else.

TODO:
 * [x] add bib entry
 * [ ] add a pyvo section (this is for someone else) -- Deferred to #37 
 * [x] probably write more text.

### CODE REVIEW

**Comment by pllim** [comment]
@keflavich , I am guessing this is not ready for review?

**Comment by nmearl** [comment]
@keflavich quick ping about the PR -- any updates to add?

**Comment by keflavich** [comment]
no but I think @ceb8 is going to help out a bit?

**Comment by ceb8** [comment]
Yes! Should be something by next week. 

@keflavich  I need another invitation to work on your repository. I thought I'd accepted but apparently not, and not the invite has expired.

**Comment by ceb8** [comment]
I can't tick the ticky boxes in the top comment since I'm not @keflavich but I've added the bib entries and more text. I can't do the pyvo part though.

**Comment by nmearl** [comment]
Who do we need to ping for pyvo?

**Comment by nmearl** [comment]
We'll be merging as-is (once passed). I've opened a new issue about adding a separate PR for the pyvo section (#37).

**Review by nmearl — APPROVED** [review]

**Comment by nmearl** [comment]
Thanks all!

**Pull request merged**
