### PR TITLE
Whatsnew section

### PR DESCRIPTION
**Pull request by nstarman**
Closes: #30
~Requires #35 (currently rebased on that branch)~ (Merged)

### CODE REVIEW

**Comment by nstarman** [comment]
oops. Sorry @mhvk. I rebased to fix a conflict and got added to all your commits...

**Comment by pllim** [comment]
We just merged #35. Please rebase. Thanks for your patience!

**Comment by nmearl** [comment]
⚠️ 🚨 Just a heads up that the current plan is to have all open PRs merged by March 11th, in preparation for a final paper draft by March 18th. Please plan accordingly!

**Comment by nstarman** [comment]
@mhvk, thanks for the comments! I think I've finished the draft of my assigned parts. Should we schedule a time to go over everything?

**Comment by mhvk** [comment]
@nstarman - sounds good. I'm in NL now, but tomorrow (Thursday) 2 PM Eastern would still work.

**Comment by nstarman** [comment]
@nmearl @adrn @pllim 

@mhvk  and I just finished a round of editing and we think it is ready for final review / merging.
Thanks!

**Comment by adrn** [comment]
Excellent -- thanks so much @nstarman and @mhvk! I will review this later today.

**Comment by mhvk** [comment]
@adrn - fine with me. Reading the whole text, I saw some duplication about stability, and surely there is some work to be done to make the style a bit more uniform. But all that is most easily done by someone looking at the whole, so the plan to merge now and edit later sounds good!

**Pull request merged**
