### PR TITLE
Minor updates to Future Plans section

### PR DESCRIPTION
**Pull request by nmearl**
Minor word flow update. Also, I found the reverse `magma` colormap really counter-intuitive (my mind wanted to associate "brighter" with "more activity"), so I suggested reversing it, but it's a personal preference.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
I'll defer the colormap change to @adrn as I think he will feel more strongly than I do in this matter. Word changes LGTM. Thanks!

**Comment by adrn** [comment]
I think the colormap direction is a subjective question :) - In my own style guide (missing link), I think of "more ink" as "more things."

**Comment by pllim** [comment]
Should we take out the colormap change as a separate PR and get the text stuff in?

**Comment by bmerry** [comment]
I also found the colormap direction non-intuitive.

**Comment by nmearl** [comment]
>I personally think that higher values should get more visual weight, because those are typically the things you want to emphasize.

Agreed! But I suppose the difference is that "visual weight" for me is the thing that stimulates the eye the most -- and since light, bright values trigger your visual sensors more, its visual weight is higher.

Anecdotally, I enjoy dark mode in most things, because I feel the bright content is easier to focus on and distinguish. Likewise, as an astronomer, I think we're trained to some degree to view "bright" things as "things that are of interest".

But honestly, it's the contrast that matters more. I'm sure people will realize that there's certainly _not_ a huge contingent of astropy contributors living in Antarctica. 😆

**Comment by adrn** [comment]
OK let's discuss the colormap question in a discussion point - can you raise it @nmearl?

**Pull request merged**
