### PR TITLE
Fix "to to"

### PR DESCRIPTION
**Pull request by bmerry**

### CODE REVIEW

**Comment by adrn** [comment]
Thanks! Some weird submodule changes are also in this PR - do you want to rebase or should I just make the edit locally?

**Comment by bmerry** [comment]
I'll try to rebase - I'm expecting to make at least one more PR so I might as well try to get my repo working.

**Comment by bmerry** [comment]
Ok I've fixed the submodule stuff and force-pushed - should be better now.

**Review by adrn — APPROVED** [review]
thanks!

**Pull request merged**
