### PR TITLE
missing "is"

### PR DESCRIPTION
**Pull request by hamogu**

### CODE REVIEW

**Comment by pllim** [comment]
I wrote that and not aware "is" is required, so I'll defer to @nmearl or @adrn to review.

**Comment by hamogu** [comment]
Oh, I'm not a native speaker - a convenient excuse to hide behind in all cases. I just thought it would sounds nice that way but I don't know if it's required (or even useful).

**Comment by bmerry** [comment]
I am a native speaker and was going to file this when I saw it had already been done.

**Review by pllim — APPROVED** [review]
Okay, native speaker wins. Thanks for the fix!

**Pull request merged**
